-- ============================================================
-- VidaMás — Phase 2A Schema Migration
-- 004_solicitud_documentos.sql
-- ============================================================
-- PURPOSE:
--   Dedicated table for tracking every document attached to a
--   solicitud. Replaces ad-hoc `docs_*` fields on the form
--   payload (those were never persisted as proper columns).
--
-- DOCUMENT TYPES:
--   ine_frente, ine_reverso, talon,
--   solicitud_p1…solicitud_p6, video
--   (type is open-text to allow new types without a migration)
--
-- LIFECYCLE:
--   upload_state:  pending → uploaded → failed
--   ocr_state:     skipped | pending → processing → done → failed
--   backup_state:  skipped | pending → done → failed
--
-- UNIQUENESS:
--   (solicitud_id, doc_type) is NOT unique — a document can be
--   replaced (e.g., agent re-uploads a blurry INE). Keep the
--   older row for audit; use `is_latest = true` to identify the
--   active version.
-- ============================================================

CREATE TABLE IF NOT EXISTS solicitud_documentos (
  id              uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  solicitud_id    uuid         NOT NULL REFERENCES solicitudes(id) ON DELETE CASCADE,

  -- Document classification
  doc_type        text         NOT NULL,
    -- 'ine_frente' | 'ine_reverso' | 'talon'
    -- 'solicitud_p1' … 'solicitud_p6'
    -- 'video'
    -- (extendable without schema change)

  -- Source of the file
  source          text         NOT NULL DEFAULT 'wizard',
    -- 'wizard'      — uploaded via the Next.js intake wizard
    -- 'paperform'   — attached to a Paperform submission
    -- 'agent'       — uploaded later by the agent (correction)
    -- 'system'      — generated by automation

  -- Storage location (Supabase Storage)
  storage_bucket  text         NOT NULL DEFAULT 'solicitud-docs',
  storage_path    text         NOT NULL,       -- e.g. "docs/{folio}/ine_frente.jpg"
  public_url      text,                        -- optional pre-signed or public URL
  file_size_bytes bigint,
  mime_type       text,

  -- Upload lifecycle
  upload_state    text         NOT NULL DEFAULT 'pending'
                    CHECK (upload_state IN ('pending', 'uploaded', 'failed')),
  upload_at       timestamptz,
  upload_error    text,

  -- OCR pipeline
  ocr_state       text         NOT NULL DEFAULT 'pending'
                    CHECK (ocr_state IN ('skipped', 'pending', 'processing', 'done', 'failed')),
  ocr_at          timestamptz,
  ocr_data        jsonb,        -- structured OCR result (e.g. INE fields)
  ocr_raw         text,         -- raw OCR text for fallback / debugging
  ocr_error       text,
  ocr_confidence  numeric(5,2), -- 0-100, model confidence if available

  -- Completeness / usefulness metadata
  is_readable     boolean,      -- true if image is legible, false if blurry/cropped
  completeness_notes text,      -- free text: "back side missing", "signature cut off", etc.

  -- Google Drive backup
  backup_state    text         NOT NULL DEFAULT 'pending'
                    CHECK (backup_state IN ('skipped', 'pending', 'done', 'failed')),
  backup_drive_id text,         -- Google Drive file ID after successful backup
  backup_at       timestamptz,
  backup_error    text,

  -- Versioning
  is_latest       boolean      NOT NULL DEFAULT true,
                    -- true = this is the active version for doc_type
                    -- false = superseded by a newer upload

  -- Audit
  created_at      timestamptz  NOT NULL DEFAULT now(),
  created_by      text,         -- agent clave or 'system'
  updated_at      timestamptz  NOT NULL DEFAULT now()
);

-- ----------------------------------------------------------
-- Indexes
-- ----------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_sol_docs_solicitud_id
  ON solicitud_documentos(solicitud_id);

CREATE INDEX IF NOT EXISTS idx_sol_docs_type
  ON solicitud_documentos(solicitud_id, doc_type);

CREATE INDEX IF NOT EXISTS idx_sol_docs_upload_state
  ON solicitud_documentos(upload_state)
  WHERE upload_state != 'uploaded';

CREATE INDEX IF NOT EXISTS idx_sol_docs_ocr_pending
  ON solicitud_documentos(ocr_state)
  WHERE ocr_state IN ('pending', 'processing');

CREATE INDEX IF NOT EXISTS idx_sol_docs_backup_pending
  ON solicitud_documentos(backup_state)
  WHERE backup_state = 'pending';

-- ----------------------------------------------------------
-- Trigger: updated_at
-- ----------------------------------------------------------

CREATE OR REPLACE FUNCTION trg_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sol_docs_updated_at ON solicitud_documentos;
CREATE TRIGGER trg_sol_docs_updated_at
  BEFORE UPDATE ON solicitud_documentos
  FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

-- ----------------------------------------------------------
-- Trigger: when a new row is inserted for a doc_type, mark
-- all older rows for the same (solicitud_id, doc_type) as
-- is_latest = false.
-- ----------------------------------------------------------

CREATE OR REPLACE FUNCTION trg_sol_docs_mark_latest()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.is_latest THEN
    UPDATE solicitud_documentos
       SET is_latest = false
     WHERE solicitud_id = NEW.solicitud_id
       AND doc_type     = NEW.doc_type
       AND id           <> NEW.id;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sol_docs_latest ON solicitud_documentos;
CREATE TRIGGER trg_sol_docs_latest
  AFTER INSERT ON solicitud_documentos
  FOR EACH ROW EXECUTE FUNCTION trg_sol_docs_mark_latest();

-- ----------------------------------------------------------
-- Convenience view: latest document per solicitud+type
-- ----------------------------------------------------------

CREATE OR REPLACE VIEW v_solicitud_documentos_latest AS
SELECT *
  FROM solicitud_documentos
 WHERE is_latest = true;

COMMENT ON VIEW v_solicitud_documentos_latest IS
  'One row per (solicitud_id, doc_type) — the active/latest version of each document.';

-- ----------------------------------------------------------
-- Convenience view: completeness summary per solicitud
-- ----------------------------------------------------------

CREATE OR REPLACE VIEW v_solicitud_doc_completeness AS
SELECT
  s.id                                          AS solicitud_id,
  s.folio,
  COUNT(d.id) FILTER (WHERE d.upload_state = 'uploaded')  AS docs_uploaded,
  COUNT(d.id) FILTER (WHERE d.upload_state = 'pending')   AS docs_pending,
  COUNT(d.id) FILTER (WHERE d.upload_state = 'failed')    AS docs_failed,
  COUNT(d.id) FILTER (WHERE d.ocr_state    = 'done')      AS docs_ocr_done,
  COUNT(d.id) FILTER (WHERE d.backup_state = 'done')      AS docs_backed_up,
  bool_and(d.is_readable IS NOT FALSE)                     AS all_readable,
  array_agg(DISTINCT d.doc_type ORDER BY d.doc_type)
    FILTER (WHERE d.is_latest = true)                      AS doc_types_present
FROM solicitudes s
LEFT JOIN solicitud_documentos d
  ON d.solicitud_id = s.id AND d.is_latest = true
GROUP BY s.id, s.folio;

COMMENT ON VIEW v_solicitud_doc_completeness IS
  'Per-solicitud document completeness rollup. Use for intake QA dashboards.';
